pipeline {
  agent any
  tools {
    maven 'maven' 
  }
  stages {
    stage ('Init') {
      steps {
        sh 'echo "Start of Job"'
      }
    }
    stage ('build') {
      steps {
        sh 'mvn package -DskipTests -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage ('Build Docker') {
      steps {
        sh 'docker build -t binarycalculator:image .'
      }
    }
    stage ('Deploy Docker'){
      steps {
        sh 'kubectl create deployment binarycalculator:image --port=8000'
        sh 'kubectl expose deployment binarycalculator-deployment --type=LoadBalancer --name=binarycalculator-service'
      }
    }
  }
}
