pipeline {
  agent any
  tools {
    maven 'maven' 
  }
  stages {
    stage ('Init') {
      steps {
        sh 'echo "Start of Job"'
        sh 'ls -la'
      }
    }
    stage ('test') {
      steps {
        sh 'mvn clean test -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage ('build') {
      steps {
        sh 'mvn package -DskipTests -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage ('Deploy') {
      steps {
        sh 'docker build -t northamerica-northeast2-docker.pkg.dev/lab-deliverable-4-cicd/sofe3980u-lab4/binarycalculator .'
        sh 'docker push northamerica-northeast2-docker.pkg.dev/lab-deliverable-4-cicd/sofe3980u-lab4/binarycalculator'
        sh 'kubectl create deployment binarycalculator-deployment --image northamerica-northeast2-docker.pkg.dev/lab-deliverable-4-cicd/sofe3980u-lab4/binarycalculator --port=8080'
        sh 'kubectl expose deployment binarycalculator-deployment --type=LoadBalancer --name=binarycalculator-service'
      }
    }
  }
}
